---
title: "Component Vol Param"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
params:
  portfolioName:
    label: "title"
    value: "Tech Stocks"
    input: text
  stock1: 
    label: "Stock 1"
    value: "GOOG"
    input: text
  stock2: 
    label: "Stock 2"
    value: "AMZN"
    input: text
  stock3: 
    label: "Stock 3"
    value: "FB"
    input: text
  w1: 
    label: "Weight 1"
    value: 25
    input: numeric
  w2: 
    label: "Weight 2"
    value: 25
    input: numeric
  w3: 
    label: "Weight 3"
    value: 50
    input: numeric
  window:
    label: "Window"
    value: 6
    input: slider
    min: 3
    max: 50
  start_date:
    label: "Start Date"
    value: "2016-01-01"
    input: date
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(tidyquant)
library(timetk)
library(DT)
library(data.table)
library(highcharter)

source("functions/helpers.r")
```

Volatility Report for `r params$portfolioName`: `r params$stock1` + `r params$stock2` + `r params$stock3`
=================================

```{r, message = FALSE, warning = FALSE}
# Let's pass parameters and get calculations
  
  returns_df <- 
    componentReturns_df(params$stock1, params$stock2, params$stock3, 
                        params$start_date) %>% 
    mutate(date = ymd(date))

  weights <- c(params$w1, params$w2, params$w3)
  
  # calculate rolling portfolio sd
  portfolio_rolling_sd <- 
  map_df(1:(nrow(returns_df) - params$window), rolling_portfolio_sd, 
         returns_df = returns_df, window = params$window, weights = weights) %>%
  mutate(date = ymd(date)) %>% 
  select(date, everything()) %>%
  tk_xts(date_var = date) %>% 
  `colnames<-`("Rolling Port SD")
  
  # calculate rolling component contributions
  portfolio_vol_components <-
    map_df(1:(nrow(returns_df)-params$window), 
           my_interval_sd, returns_df = returns_df, 
           weights = weights, window = params$window) %>%
    mutate_all(funs(round(., 3))) %>% 
    mutate(date = ymd(date)) %>%
    select(date, everything()) %>%
    tk_xts(date_var = date)
  # an xts comes out of this
```

Row 1
-----------------------------------------

### Portfolio Rolling Volatility

```{r, warning = FALSE}
highchart(type = "stock") %>%
  hc_title(text = "Portfolio Rolling Volatility") %>%
  hc_add_series(portfolio_rolling_sd, name = "Portfolio Volatility", color = 'green') %>%
  hc_add_theme(hc_theme_flat()) %>%
  hc_yAxis(labels = list(format = "{value}%"), opposite = FALSE) %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE)
```

Row 2
----------------------------------------

### Asset Contribution to Total Volatility

```{r, warning= FALSE}
  highchart(type = "stock") %>% 
    hc_title(text = "Volatility Contribution by Asset") %>%
    hc_add_series(portfolio_vol_components[, 1], 
                  name = names(portfolio_vol_components[, 1])) %>%
    hc_add_series(portfolio_vol_components[, 2], 
                  name = names(portfolio_vol_components[, 2])) %>%
    hc_add_series(portfolio_vol_components[, 3], 
                  name = names(portfolio_vol_components[, 3])) %>%
    hc_add_theme(hc_theme_flat()) %>%
    hc_yAxis(labels = list(format = "{value}%"), opposite = FALSE) %>%
    hc_navigator(enabled = FALSE) %>% 
    hc_scrollbar(enabled = FALSE)

```


